#!/usr/bin/env bash
#Displays information about subdomains

display_subdomain_info() {
    local domain=$1
    local subdomain=$2
    
    dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk -v sd="$subdomain" '{print "The subdomain " sd " is a " $4 " record and points to " $5}'
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    display_subdomain_info "$domain" "www"
    display_subdomain_info "$domain" "lb-01"
    display_subdomain_info "$domain" "web-01"
    display_subdomain_info "$domain" "web-02"
else
    display_subdomain_info "$domain" "$subdomain"
fi
